### ISSUE TITLE
run app is error

### ISSUE THREAD

**Issue by luodongwen** [amitshekhariitbhu/AndroidTensorFlowMachineLearningExample#9]
Process: com.mindorks.tensorflowexample, PID: 517
                                                                            java.lang.RuntimeException: Error initializing TensorFlow!
                                                                                at com.mindorks.tensorflowexample.MainActivity$5.run(MainActivity.java:158)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                at java.lang.Thread.run(Thread.java:818)
                                                                             Caused by: java.lang.RuntimeException: Native TF methods not found; check that the correct native libraries are present and loaded.
                                                                                at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:57)
                                                                                at com.mindorks.tensorflowexample.TensorFlowImageClassifier.create(TensorFlowImageClassifier.java:108)
                                                                                at com.mindorks.tensorflowexample.MainActivity$5.run(MainActivity.java:147)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                at java.lang.Thread.run(Thread.java:818)

**Comment by liyirui-git** [comment]
yeah, i also crash in com.mindorks.tensorflowexample
